---
title: "Introduction"
author: "Alberta Biodiversity Monitoring Institute"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Introduction}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r setup,include=FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
#suppressPackageStartupMessages(library(abmidata))
```

This article describes the scope and application of the data and information
provided by the [Alberta Biodiversity Monitoring Institute](https://abmi.ca).

## Introduction

Historically, ecological monitoring has occurred over small areas and short time periods,
providing limited information to managers and policy analysts. Thus in Alberta, as elsewhere,
natural resource management has proceeded without sufficient feedback on ecological change,
making it difficult to gauge success in meeting land-use objectives. Large-scale, long-term
monitoring is the most certain means of obtaining information to support natural resource policy
development and evaluation.

The Alberta Biodiversity Monitoring Institute (ABMI) is a large-scale, long-term monitoring
program designed to support natural resource decision-making. The ABMI provides relevant,
timely and credible scientific knowledge on the state of provincial biodiversity. Services offered by
the Institute include: public access to raw data, and public access to value-added information
products. These two services are designed to encourage:

1. Application – Return on investment in biodiversity monitoring is realized only if the resulting knowledge is applied. Public and timely access to ABMI products encourages the use of information in decision-making processes including resource management and public policy.
2. Transparency – Scientific credibility is at the foundation of the ABMI. Scientific inference produced by the Institute, or any other third-party, must be subject to independent audit and verification by the greater research and management community.
3. Efficiency – Comprehensive, science-based biodiversity data is expensive to collect and manage. Use of this information by many stakeholders will reduce redundancy and costs in provincial environmental monitoring.
4. Innovation – Long-term, scientifically rigorous environmental data sets are highly valuable to the research and management communities. By making the ABMI's data publicly available, significant innovation is anticipated to occur in the discipline of sustainable resource management.

However providing public access to information products creates opportunity for the inappropriate analysis and/or interpretation of ABMI information. This report provides general guidance for the analysis, interpretation, and application of ABMI data and information products.

## The Application of ABMI Information

The ABMI's information has significant application to the following regional and provincial management areas:

1. Strategic land-use planning,
2. Cumulative impact assessment and management,
3. Performance monitoring (effectiveness monitoring and stewardship reporting),
4. Status reporting, and
5. Adaptive management,

Where is the application of the ABMI's information most relevant?
The ABMI is a key component in achieving the vision of the sustainable resource management.
Under sustainable resource management systems, monitoring information is needed to assess
the effectiveness of policies and programs. Monitoring may confirm effective action or may
provide insight into what changes might be needed when desired outcomes are not being
attained. As applied to biodiversity, monitoring should assess the effectiveness of resource
management and support its improvement. The ABMI's information can be used to support the
preparation of management plans and responses, as well as identification of any gaps in
understanding relationships associated with changes in biodiversity.

This description of the ABMI's strengths is not meant to be restrictive. The ABMI recognizes, and
encourages, the innovative use of the Institute's information. However, we strongly encourage
that practitioners making use of ABMI information consider the guidance provided below.

## Raw Data Guidance

The ABMI collects abiotic and biotic data using numerous filed and remote sensing protocols.
After undergoing quality control by the ABMI, the data is publicly available without further
modification. Raw and compiled data is publicly accessible at the scale of individual points.
When using the ABMI's raw data the following guidance is further suggested:

### Statistical power

Statistical power, defined as the ability to detect a significant change or trend, is influenced by
many factors including: type of statistics used, magnitude of change that occurred, desired
significance level ($\alpha$), number of samples, frequency of samples through time, detectability of the
indicator, spatial and temporal variability in the indicator, and measurement error. Drawing valid
statistical inference from ABMI data is conditional on the clear and reasonable treatment of each
of these factors.

### Spatial Scale

The ABMI uses a large-scale, systematic sampling design to collect unbiased data on variety of
biodiversity indicators and human land-use practices. This sampling design was implemented in
order to draw inference about the provincial and regional state of these indicators. In general, the
ABMI considers a “region” as a continuous or discontinuous area encompassing 50 or more
sampling points. The ABMI is not optimally designed to provide results at the scale of individual
points or very small regions (e.g., less than 50 points).

### Correlative Inference

Knowing that there are changes in biodiversity is of limited management value if the potential
causes of the changes are not understood. Thus, the ABMI is designed to identify correlative
associations between changes in biota, changes in habitat and changes in human land-use
activities. The ABMI's data can be used to establish correlations and enable research hypotheses
to be developed about the potential cause-and-effect relationships between biota, habitat, and
human land-use activities. Applied research is necessary to more effectively evaluate hypotheses
and establish cause-and-effect relationships. The ABMI sampling design cannot be used to
replace basic or applied research.

### Rare or Under-represented Elements

The ABMI is designed to sample and report on the state of common species, habitats, and
human land-use activities. The ABMI is not designed to survey very uncommon elements as
large-scale systematic sampling designs are not an optimal strategy for sampling highly patchy or
uncommon resources.

Many species and habitats present in the ABMI's data will only occur one or several times. This
may be because the element is rare to Alberta's landscapes – as is the case with species listed
as Rare and Endangered. In addition, many elements may occur one or several times in the
ABMI's data because the Institutes protocols are not optimally designed to sample all species.
For example, owl species are expected to be under represented in the Institutes data because
the sampling protocols employed by the institute are not optimally designed to survey this group.
Data on rare or under-represented species should be analyzed and interpreted cautiously.

### Ethical Behaviour

The responsible analysis and interpretation of data requires honesty and conscientiousness. The
ABMI holds itself to the highest ethical standards including operational transparency, honesty,
conscientiousness and integrity. The Institute strongly encourages the responsible and ethical
evaluation and interpretation of program information. For a complete discussion of the ethical
behaviour endorsed by the ABMI please see [Honor in Science published by Sigma Xi](https://www.sigmaxi.org/programs/ethics-and-research/ethics-publications).

## Disclosure

It is strongly recommended that any use of ABMI information products include the
following statements of disclosure:

1. the version and type of ABMI data used,
2. if appropriate, the type and source of additional, non-ABMI data used in analysis,
3. a full description of any analysis, and
4. the person(s) or organization(s) conducting the analysis.

## Conclusion

The value of biodiversity information is increased through the responsible analysis, interpretation
and application within the context of resource management and policy. Participants in decision-
making must recognize both the strengths and limitations of the knowledge used to facilitate
these processes. The guidance provided in this report is meant to encourage the responsible and
ethical application of knowledge generated through the use of ABMI data and information
products.
